### ISSUE TITLE
Update installation instructions for bash to make it work on macOS Sierra

### ISSUE THREAD

**Issue by pioterj** [eriwen/gradle-completion#15]
Current installation instructions for bash didn't work for me on macOS Sierra. It currently says to update`.bashrc`. I had to update `.bash_profile` to make it work. [This article](http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html) explains the difference between `.bashrc` and `.bash_profile`, and here's what it says about Mac OS X (which is likely to be the case for macOS Sierra too):

> An exception to the terminal window guidelines is Mac OS X’s Terminal.app, which runs a login shell by default for each new terminal window, calling .bash_profile instead of .bashrc. Other GUI terminal emulators may do the same, but most tend not to.

**Comment by eriwen** [comment]
Closing as complete — thanks!
