### ISSUE TITLE
Error using in zsh

### ISSUE THREAD

**Issue by staffanf** [eriwen/gradle-completion#7]
I get error when trying to use this script using zsh + oh-my-zsh.
Using commit 511ec3d

```
Ξ external/jenkins git:(master) ▶ gradle --
_gradle:83: parse error near `]]'
_gradle:83: parse error near `]]'
_gradle:83: parse error near `]]'
```

The lines I added to .zshrc
```
zstyle ':completion:*' use-cache on
export PATH=".:$PATH"
fpath=(/home/stalle/.zsh/gradle-completion $fpath)
```

**Comment by eriwen** [comment]
@staffanf Which version of zsh are you using? This sounds similar to #4 where we discovered zsh 5.0.5 has a bug and upgrading fixed the issue.

**Comment by staffanf** [comment]
Built and updated to zsh 5.3.1. Now this bug seems to have gone way....
If I now do `gradle [TAB]` in a `gradle init --type basic` dir, I get:
`zsh: do you wish to see all 262 possibilities (116 lines)? ` where the last 2 lines looks like
```
'test'.    [incubating]    all       buildscript    components       declared        dependency    files.    help    insight    message.    new    produced    properties    runnable    sub-projects    the      
Gradle     a               build.    by             configuration    dependencies    dependent     from      in      into       model       of     project     root          specific    tasks           wrapper 
```
This looks kinda messed up... maybe a separate bug though...

**Comment by eriwen** [comment]
Thanks for the additional report @staffanf. It is captured in #8.
